### ISSUE TITLE
Create code-of-conduct.md

### ISSUE THREAD

**Issue by jeffsaelens** [cloud-native-principles/cloud-native-principles#12]
We need to draft a code of conduct for the cloud-native-principles to follow. I suggest we conform to the [CNCF's Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)

# Code of Conduct 

The cloud-native-principles community follows the: 
[CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).

**Comment by taylor** [comment]
+1 for adopting  CNCF's Code of Conduct

**Comment by fkautz** [comment]
+1

**Comment by taylor** [comment]
An alternative to just referencing the CNCF code of conduct would be to include the content directly from https://github.com/cncf/foundation/blob/master/code-of-conduct.md or using the content for the upstream reference CNCF based theirs on, [Contributor Covenant CoC version 1.2.0](https://www.contributor-covenant.org/version/1/2/0/code-of-conduct/).
