### ISSUE TITLE
Add LICENSE to repo and section in README

### ISSUE THREAD

**Issue by taylor** [cloud-native-principles/cloud-native-principles#5]
Add a LICENSE file to the repo and a section in the main README about the license used.

I suggest using [Creative Commons Attribution 4.0 International (CC BY 4.0) 
](https://creativecommons.org/licenses/by/4.0/).  

> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
> for any purpose, even commercially.
> Under the following terms:
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> 
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

**Comment by jeffsaelens** [comment]
I second this suggestion.

**Comment by fkautz** [comment]
nice!

**Comment by dabernie** [comment]
Same here
